### ISSUE TITLE
Can hoedur reproducer output more execution log like fuzzware 

### ISSUE THREAD

**Issue by dingiso** [fuzzware-fuzzer/hoedur-experiments#2]
Hi Simon Wörner and hoedur maintainers,

I have tried the reproducer but it only tell me the where the crash is without any execution log

Can hoedur output more execution log as fuzzware ? 

Thanks,
Dingisoul

**Comment by SWW13** [comment]
Hi,

if you are running an reproducer, e.g. `run_reproducer_CVE-2022-39274.sh` you can simple append the argument `--trace` to enable an extended trace output:

```bash
04-prev-unknown-vulns/repro-run-scripts/run_reproducer_CVE-2022-39274.sh --trace
```

This will print all visited basic blocks and any memory interaction (RAM + MMIO read/write). However this can slow down the execution by a factor of up to 10x, therefore we disabled it by default.
I also recommend piping the output into a file as it most likely will overflow your terminal buffer.

**Comment by dingiso** [comment]
Hi Simon Wörner ,

It's great !!

Thanks,
Dingisoul
