### ISSUE TITLE
run_fuzzware_docker script might not work

### ISSUE THREAD

**Issue by xidoo123** [fuzzware-fuzzer/hoedur-experiments#7]
Hi,

In the script `scripts/fuzzware/run_fuzzware_docker.sh`, I find docker sometimes doesn't like `$docker_options` if I run the script in another script (e.g. if I want to batch generate many many configs).

```
docker: invalid reference format.
See 'docker run --help'.
```

After I removed the double quote it works. I'm not a shell expert but if you just replace `$docker_options` with `""` it still not works. So I think this should be the right fix?

```sh
docker run \
    --rm -i \
    --user "$(id -u):$(id -g)" \
    --env "HOME=/home/user" \
    --env "PYTHON_EGG_CACHE=/tmp/.cache" \
    $docker_options \   <--- instead of "$docker_options"
    --mount type=bind,source="$(realpath $experiments_rootdir)",target=/home/user/fuzzware/targets \
    "fuzzware:fuzzware-hoedur-eval" $@
```

**Comment by SWW13** [comment]
Thanks for the report :)

fixed in 2babc78b72b1331b3122c11f170e9367132b8aa2
